version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: json_share_mysql
    env_file: .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: json_share_app_test
    env_file: .env
    ports:
      - "${NUXT_PORT}:3000"
    depends_on:
      mysql:
        condition: service_healthy
