version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: json_share_mysql
    env_file: .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: ${DOCKER_USERNAME}/json_share:latest
    container_name: json_share_app_prod
    env_file: .env
    ports:
      - "${NUXT_PORT}:3000"
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
