FROM node:18-alpine

WORKDIR /app

# 使用非root用户运行（使用动态GID）
RUN addgroup -S nuxt && \
    adduser -S -G nuxt -s /bin/sh nuxt

# 复制package.json和package-lock.json
COPY package*.json ./

# 安装依赖
RUN npm install

# 复制应用代码
COPY . .

# 构建应用
RUN npm run build

# 将所有权限授予nuxt用户
RUN chown -R nuxt:nuxt /app

# 切换到nuxt用户
USER nuxt


# 暴露端口
EXPOSE 3000

# 启动生产服务器
CMD ["node", ".output/server/index.mjs"] 