version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: json_share_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: json_share
      MYSQL_USER: json_share_user
      MYSQL_PASSWORD: json_share_password
    ports:
      - "3306:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: json_share_app
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=json_share_user
      - MYSQL_PASSWORD=json_share_password
      - MYSQL_DATABASE=json_share
    depends_on:
      mysql:
        condition: service_healthy 